/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountCallbackRouteImport } from './routes/account.callback'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCallbackRoute = AccountCallbackRouteImport.update({
  id: '/account/callback',
  path: '/account/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/callback': typeof AccountCallbackRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/callback': typeof AccountCallbackRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/callback': typeof AccountCallbackRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favourites'
    | '/sitemap.xml'
    | '/account/callback'
    | '/collections/$handle'
    | '/pages/$slug'
    | '/policies/$slug'
    | '/product/$handle'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favourites'
    | '/sitemap.xml'
    | '/account/callback'
    | '/collections/$handle'
    | '/pages/$slug'
    | '/policies/$slug'
    | '/product/$handle'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/favourites'
    | '/sitemap.xml'
    | '/account/callback'
    | '/collections/$handle'
    | '/pages/$slug'
    | '/policies/$slug'
    | '/product/$handle'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesRoute: typeof FavouritesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AccountCallbackRoute: typeof AccountCallbackRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/callback': {
      id: '/account/callback'
      path: '/account/callback'
      fullPath: '/account/callback'
      preLoaderRoute: typeof AccountCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesRoute: FavouritesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AccountCallbackRoute: AccountCallbackRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  PagesSlugRoute: PagesSlugRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
